name: high-cloud-cre-2026

channels:
  - conda-forge

dependencies:
  - python=3.12
  - numpy=2.2.0
  - cartopy
  - cmcrameri
  - ipykernel
  - matplotlib
  - netcdf4
  - pandas
  - scipy
  - statsmodels
  - scikit-learn
  - xarray
